

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/m-greeballah/odoo-gitops.git
    targetRevision: HEAD
    path: helm/odoo
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: odoo-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true